spring:
  profiles:
    active: @db_env@
  redis:
    host: 47.107.177.115
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
  cache:
    type: redis

  #rabbitmq:
    #host: 192.168.124.6
    #username: guest
    #password: guest
    #port: 5672
    #publisher-returns: true
    #publisher-confirm-type: correlated

  datasource:
    username: root
    password: qwer1234
    #url: jdbc:mysql://localhost:3306/my_test?useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 使用alibaba的druid连接池、监控
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
      max-wait: 5000
      min-idle: 5
      initial-size: 2
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
      web-stat-filter:
        enabled: true
        exclusions: js,gif,jpg,png,css,ico,/druid/*
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid@2019


# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: springbootlearn.springbootredis.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: springbootlearn.springbootredis.entity


#showSql
logging:
  level:
    com:
      example:
        mapper: debug

  config: classpath:logback-${spring.profiles.active}.xml