spring:
  datasource:
    url: jdbc:mysql://47.107.177.115:3306/plugin_dev?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true